#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Wed Oct  9 23:04:28 2013

import wx
import wx.grid

# begin wxGlade: extracode
# end wxGlade


class MainWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainWindow.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "Quit", "", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        self.frame_1_menubar.Append(wxglade_tmp_menu, "About")
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.rootTabs = wx.Notebook(self, -1, style=0)
        self.match_main = wx.Panel(self.rootTabs, -1)
        self.match_teamLabel = wx.StaticText(self.match_main, -1, "Team:")
        self.match_teamSelect = wx.SpinCtrl(self.match_main, -1, "", min=0, max=100)
        self.match_enable = wx.ToggleButton(self.match_main, -1, "Match Enable")
        self.match_forceStart = wx.Button(self.match_main, -1, "Force Start")
        self.match_forceStop = wx.Button(self.match_main, -1, "Force Stop")
        self.match_pause = wx.ToggleButton(self.match_main, -1, "Pause")
        self.match_time = wx.StaticText(self.match_main, -1, "Match Not Running", style=wx.ALIGN_CENTRE)
        self.match_assignPenalty = wx.Button(self.match_main, -1, "Assign Penalty")
        self.ranks_main = wx.Panel(self.rootTabs, -1)
        self.rank_modify = wx.Button(self.ranks_main, -1, "Modify Rankings")
        self.rank_updateDisplay = wx.Button(self.ranks_main, -1, "Force Update of Remote")
        self.rank_list = wx.grid.Grid(self.ranks_main, -1, size=(1, 1))
        self.teams_main = wx.Panel(self.rootTabs, -1)
        self.teams_add = wx.Button(self.teams_main, -1, "Add Team")
        self.teams_remove = wx.Button(self.teams_main, -1, "Remove Team")
        self.teams_modify = wx.Button(self.teams_main, -1, "Modify Team")
        self.teams_list = wx.grid.Grid(self.teams_main, -1, size=(1, 1))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.menuQuit, id=-1)
        self.Bind(wx.EVT_SPINCTRL, self.matchSelectTeam, self.match_teamSelect)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.matchEnable, self.match_enable)
        self.Bind(wx.EVT_BUTTON, self.matchForceStart, self.match_forceStart)
        self.Bind(wx.EVT_BUTTON, self.matchForceStop, self.match_forceStop)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.matchPauseTime, self.match_pause)
        self.Bind(wx.EVT_BUTTON, self.matchAssignPenalty, self.match_assignPenalty)
        self.Bind(wx.EVT_BUTTON, self.rankingsModify, self.rank_modify)
        self.Bind(wx.EVT_BUTTON, self.rankingsResetRemote, self.rank_updateDisplay)
        self.Bind(wx.EVT_BUTTON, self.teamsAdd, self.teams_add)
        self.Bind(wx.EVT_BUTTON, self.teamsRemove, self.teams_remove)
        self.Bind(wx.EVT_BUTTON, self.teamsModify, self.teams_modify)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainWindow.__set_properties
        self.SetTitle("RAS Scoreboard Control")
        self.match_teamSelect.SetMinSize((225, 25))
        self.match_time.SetFont(wx.Font(24, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.rank_list.CreateGrid(10, 1)
        self.rank_list.EnableEditing(0)
        self.rank_list.EnableDragColSize(0)
        self.rank_list.SetColLabelValue(0, "Team Name")
        self.teams_list.CreateGrid(9, 2)
        self.teams_list.EnableEditing(0)
        self.teams_list.EnableDragColSize(0)
        self.teams_list.SetColLabelValue(0, "Team Name")
        self.teams_list.SetColLabelValue(1, "Number")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainWindow.__do_layout
        rootSizer = wx.BoxSizer(wx.VERTICAL)
        sizer_teamsData = wx.BoxSizer(wx.VERTICAL)
        sizer_teamTable = wx.BoxSizer(wx.HORIZONTAL)
        sizer_teamsModify = wx.BoxSizer(wx.HORIZONTAL)
        sizer_ranksMain = wx.BoxSizer(wx.VERTICAL)
        sizer_rankTable = wx.BoxSizer(wx.HORIZONTAL)
        sizer_rankOverrides = wx.BoxSizer(wx.HORIZONTAL)
        sizer_matchMain = wx.BoxSizer(wx.VERTICAL)
        sizer_timeOverrides = wx.BoxSizer(wx.HORIZONTAL)
        sizer_selectTeam = wx.BoxSizer(wx.HORIZONTAL)
        sizer_selectTeam.Add(self.match_teamLabel, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL, 5)
        sizer_selectTeam.Add(self.match_teamSelect, 0, 0, 0)
        sizer_selectTeam.Add(self.match_enable, 0, 0, 0)
        sizer_matchMain.Add(sizer_selectTeam, 0, wx.ALL, 6)
        sizer_timeOverrides.Add(self.match_forceStart, 0, wx.EXPAND, 0)
        sizer_timeOverrides.Add(self.match_forceStop, 0, wx.EXPAND, 0)
        sizer_timeOverrides.Add(self.match_pause, 0, wx.EXPAND, 0)
        sizer_matchMain.Add(sizer_timeOverrides, 0, wx.ALL, 5)
        sizer_matchMain.Add(self.match_time, 0, wx.ALL | wx.EXPAND, 4)
        sizer_matchMain.Add(self.match_assignPenalty, 0, wx.ALL | wx.EXPAND, 4)
        self.match_main.SetSizer(sizer_matchMain)
        sizer_rankOverrides.Add(self.rank_modify, 0, wx.ALL, 5)
        sizer_rankOverrides.Add(self.rank_updateDisplay, 0, wx.ALL, 5)
        sizer_ranksMain.Add(sizer_rankOverrides, 0, 0, 0)
        sizer_rankTable.Add(self.rank_list, 1, wx.EXPAND, 0)
        sizer_rankTable.Add((0, 175), 0, 0, 0)
        sizer_ranksMain.Add(sizer_rankTable, 0, wx.EXPAND, 10)
        self.ranks_main.SetSizer(sizer_ranksMain)
        sizer_teamsModify.Add(self.teams_add, 0, wx.ALL, 5)
        sizer_teamsModify.Add(self.teams_remove, 0, wx.ALL, 5)
        sizer_teamsModify.Add(self.teams_modify, 0, wx.ALL, 5)
        sizer_teamsData.Add(sizer_teamsModify, 0, wx.EXPAND, 0)
        sizer_teamTable.Add(self.teams_list, 1, wx.EXPAND, 0)
        sizer_teamTable.Add((0, 150), 0, 0, 0)
        sizer_teamsData.Add(sizer_teamTable, 0, wx.EXPAND, 0)
        self.teams_main.SetSizer(sizer_teamsData)
        self.rootTabs.AddPage(self.match_main, "Main")
        self.rootTabs.AddPage(self.ranks_main, "Rankings")
        self.rootTabs.AddPage(self.teams_main, "Teams")
        rootSizer.Add(self.rootTabs, 1, wx.EXPAND, 0)
        self.SetSizer(rootSizer)
        rootSizer.Fit(self)
        self.Layout()
        # end wxGlade

    def menuQuit(self, event):  # wxGlade: MainWindow.<event_handler>
        print "Event handler `menuQuit' not implemented!"
        event.Skip()

    def matchSelectTeam(self, event):  # wxGlade: MainWindow.<event_handler>
        print "Event handler `matchSelectTeam' not implemented!"
        event.Skip()

    def matchEnable(self, event):  # wxGlade: MainWindow.<event_handler>
        print "Event handler `matchEnable' not implemented!"
        event.Skip()

    def matchForceStart(self, event):  # wxGlade: MainWindow.<event_handler>
        print "Event handler `matchForceStart' not implemented!"
        event.Skip()

    def matchForceStop(self, event):  # wxGlade: MainWindow.<event_handler>
        print "Event handler `matchForceStop' not implemented!"
        event.Skip()

    def matchPauseTime(self, event):  # wxGlade: MainWindow.<event_handler>
        print "Event handler `matchPauseTime' not implemented!"
        event.Skip()

    def matchAssignPenalty(self, event):  # wxGlade: MainWindow.<event_handler>
        print "Event handler `matchAssignPenalty' not implemented!"
        event.Skip()

    def rankingsModify(self, event):  # wxGlade: MainWindow.<event_handler>
        print "Event handler `rankingsModify' not implemented!"
        event.Skip()

    def rankingsResetRemote(self, event):  # wxGlade: MainWindow.<event_handler>
        print "Event handler `rankingsResetRemote' not implemented!"
        event.Skip()

    def teamsAdd(self, event):  # wxGlade: MainWindow.<event_handler>
        print "Event handler `teamsAdd' not implemented!"
        event.Skip()

    def teamsRemove(self, event):  # wxGlade: MainWindow.<event_handler>
        print "Event handler `teamsRemove' not implemented!"
        event.Skip()

    def teamsModify(self, event):  # wxGlade: MainWindow.<event_handler>
        print "Event handler `teamsModify' not implemented!"
        event.Skip()

# end of class MainWindow
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    mainFrame = MainWindow(None, -1, "")
    app.SetTopWindow(mainFrame)
    mainFrame.Show()
    app.MainLoop()
