#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Tue Oct  1 18:04:54 2013

import wx
import wx.grid

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "Quit", "", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        self.frame_1_menubar.Append(wxglade_tmp_menu, "About")
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.match_main = wx.Panel(self.notebook_1, -1)
        self.match_teamLabel = wx.StaticText(self.match_main, -1, "Team:")
        self.match_teamSelect = wx.SpinCtrl(self.match_main, -1, "", min=0, max=100)
        self.match_enable = wx.ToggleButton(self.match_main, -1, "Match Enable")
        self.match_forceStart = wx.Button(self.match_main, -1, "Force Start")
        self.match_forceStop = wx.Button(self.match_main, -1, "Force Stop")
        self.match_pause = wx.ToggleButton(self.match_main, -1, "Pause")
        self.match_time = wx.StaticText(self.match_main, -1, "Match Not Running", style=wx.ALIGN_CENTRE)
        self.match_assignPenalty = wx.Button(self.match_main, -1, "Assign Penalty")
        self.ranks_main = wx.Panel(self.notebook_1, -1)
        self.rank_list = wx.grid.Grid(self.ranks_main, -1, size=(1, 1))
        self.rank_modify = wx.Button(self.ranks_main, -1, "Modify Rankings")
        self.rank_updateDisplay = wx.Button(self.ranks_main, -1, "Force Update of Remote")
        self.teams_main = wx.Panel(self.notebook_1, -1)
        self.teams_list = wx.grid.Grid(self.teams_main, -1, size=(1, 1))
        self.teams_add = wx.Button(self.teams_main, -1, "Add Team")
        self.teams_remove = wx.Button(self.teams_main, -1, "Remove Team")
        self.teams_modify = wx.Button(self.teams_main, -1, "Modify Team")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("RAS Scoreboard Control")
        self.match_teamSelect.SetMinSize((225, 25))
        self.match_time.SetFont(wx.Font(24, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.rank_list.CreateGrid(10, 1)
        self.rank_list.EnableEditing(0)
        self.rank_list.EnableDragColSize(0)
        self.rank_list.SetColLabelValue(0, "Team Name")
        self.teams_list.CreateGrid(9, 2)
        self.teams_list.EnableEditing(0)
        self.teams_list.EnableDragColSize(0)
        self.teams_list.SetColLabelValue(0, "Team Name")
        self.teams_list.SetColLabelValue(1, "Number")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.match_teamLabel, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL, 5)
        sizer_4.Add(self.match_teamSelect, 0, 0, 0)
        sizer_4.Add(self.match_enable, 0, 0, 0)
        sizer_3.Add(sizer_4, 0, wx.ALL, 6)
        sizer_5.Add(self.match_forceStart, 0, wx.EXPAND, 0)
        sizer_5.Add(self.match_forceStop, 0, wx.EXPAND, 0)
        sizer_5.Add(self.match_pause, 0, wx.EXPAND, 0)
        sizer_3.Add(sizer_5, 0, wx.ALL, 5)
        sizer_3.Add(self.match_time, 0, wx.ALL | wx.EXPAND, 4)
        sizer_3.Add(self.match_assignPenalty, 0, wx.ALL | wx.EXPAND, 4)
        self.match_main.SetSizer(sizer_3)
        sizer_10.Add(self.rank_list, 1, wx.EXPAND, 0)
        sizer_10.Add((0, 175), 0, 0, 0)
        sizer_6.Add(sizer_10, 0, wx.EXPAND, 0)
        sizer_7.Add(self.rank_modify, 0, wx.ALL, 5)
        sizer_7.Add(self.rank_updateDisplay, 0, wx.ALL, 5)
        sizer_6.Add(sizer_7, 0, 0, 0)
        self.ranks_main.SetSizer(sizer_6)
        sizer_11.Add(self.teams_list, 1, wx.EXPAND, 0)
        sizer_11.Add((0, 150), 0, 0, 0)
        sizer_8.Add(sizer_11, 0, wx.EXPAND, 0)
        sizer_9.Add(self.teams_add, 0, wx.ALL, 5)
        sizer_9.Add(self.teams_remove, 0, wx.ALL, 5)
        sizer_9.Add(self.teams_modify, 0, wx.ALL, 5)
        sizer_8.Add(sizer_9, 0, wx.EXPAND, 0)
        self.teams_main.SetSizer(sizer_8)
        self.notebook_1.AddPage(self.match_main, "Main")
        self.notebook_1.AddPage(self.ranks_main, "Rankings")
        self.notebook_1.AddPage(self.teams_main, "Teams")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
